/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppEnvironmentsRouteImport } from './routes/_app/environments'
import { Route as AppEndpointsRouteImport } from './routes/_app/endpoints'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppEndpointsNewRouteImport } from './routes/_app/endpoints.new'
import { Route as AppEndpointsIdRouteImport } from './routes/_app/endpoints.$id'
import { Route as AppEndpointsIdEditRouteImport } from './routes/_app/endpoints.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEnvironmentsRoute = AppEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => AppRoute,
} as any)
const AppEndpointsRoute = AppEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppEndpointsNewRoute = AppEndpointsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppEndpointsRoute,
} as any)
const AppEndpointsIdRoute = AppEndpointsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEndpointsRoute,
} as any)
const AppEndpointsIdEditRoute = AppEndpointsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppEndpointsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/endpoints': typeof AppEndpointsRouteWithChildren
  '/environments': typeof AppEnvironmentsRoute
  '/endpoints/$id': typeof AppEndpointsIdRouteWithChildren
  '/endpoints/new': typeof AppEndpointsNewRoute
  '/endpoints/$id/edit': typeof AppEndpointsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/endpoints': typeof AppEndpointsRouteWithChildren
  '/environments': typeof AppEnvironmentsRoute
  '/endpoints/$id': typeof AppEndpointsIdRouteWithChildren
  '/endpoints/new': typeof AppEndpointsNewRoute
  '/endpoints/$id/edit': typeof AppEndpointsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/endpoints': typeof AppEndpointsRouteWithChildren
  '/_app/environments': typeof AppEnvironmentsRoute
  '/_app/endpoints/$id': typeof AppEndpointsIdRouteWithChildren
  '/_app/endpoints/new': typeof AppEndpointsNewRoute
  '/_app/endpoints/$id/edit': typeof AppEndpointsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/alerts'
    | '/dashboard'
    | '/endpoints'
    | '/environments'
    | '/endpoints/$id'
    | '/endpoints/new'
    | '/endpoints/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/alerts'
    | '/dashboard'
    | '/endpoints'
    | '/environments'
    | '/endpoints/$id'
    | '/endpoints/new'
    | '/endpoints/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/endpoints'
    | '/_app/environments'
    | '/_app/endpoints/$id'
    | '/_app/endpoints/new'
    | '/_app/endpoints/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/environments': {
      id: '/_app/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof AppEnvironmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/endpoints': {
      id: '/_app/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof AppEndpointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/endpoints/new': {
      id: '/_app/endpoints/new'
      path: '/new'
      fullPath: '/endpoints/new'
      preLoaderRoute: typeof AppEndpointsNewRouteImport
      parentRoute: typeof AppEndpointsRoute
    }
    '/_app/endpoints/$id': {
      id: '/_app/endpoints/$id'
      path: '/$id'
      fullPath: '/endpoints/$id'
      preLoaderRoute: typeof AppEndpointsIdRouteImport
      parentRoute: typeof AppEndpointsRoute
    }
    '/_app/endpoints/$id/edit': {
      id: '/_app/endpoints/$id/edit'
      path: '/edit'
      fullPath: '/endpoints/$id/edit'
      preLoaderRoute: typeof AppEndpointsIdEditRouteImport
      parentRoute: typeof AppEndpointsIdRoute
    }
  }
}

interface AppEndpointsIdRouteChildren {
  AppEndpointsIdEditRoute: typeof AppEndpointsIdEditRoute
}

const AppEndpointsIdRouteChildren: AppEndpointsIdRouteChildren = {
  AppEndpointsIdEditRoute: AppEndpointsIdEditRoute,
}

const AppEndpointsIdRouteWithChildren = AppEndpointsIdRoute._addFileChildren(
  AppEndpointsIdRouteChildren,
)

interface AppEndpointsRouteChildren {
  AppEndpointsIdRoute: typeof AppEndpointsIdRouteWithChildren
  AppEndpointsNewRoute: typeof AppEndpointsNewRoute
}

const AppEndpointsRouteChildren: AppEndpointsRouteChildren = {
  AppEndpointsIdRoute: AppEndpointsIdRouteWithChildren,
  AppEndpointsNewRoute: AppEndpointsNewRoute,
}

const AppEndpointsRouteWithChildren = AppEndpointsRoute._addFileChildren(
  AppEndpointsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEndpointsRoute: typeof AppEndpointsRouteWithChildren
  AppEnvironmentsRoute: typeof AppEnvironmentsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEndpointsRoute: AppEndpointsRouteWithChildren,
  AppEnvironmentsRoute: AppEnvironmentsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
